# Generated by Django 3.2.6 on 2021-08-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20210815_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(default='Prashant', max_length=150),
            preserve_default=False,
        ),
    ]
