# Generated by Django 3.2.6 on 2021-08-16 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='on_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
