# Generated by Django 3.2.6 on 2021-08-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_on_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='on_date',
            field=models.DateField(null=True),
        ),
    ]
