# Generated by Django 3.2.6 on 2021-08-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('sms_body', models.TextField(max_length=2000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
