# Generated by Django 3.2.6 on 2021-08-15 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_paper_number', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(65)])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('mobile_number', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField(blank=True, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
